#!/bin/sh
#
# Copyright (C) 2000-2021 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# Run test-plugin-fd.  Note, this plugin is for testing
#   new features and probably should not be run in normal
#   testing
#
TestName="metadata-test"
JobName=TestPluginTest
. scripts/functions

scripts/cleanup
scripts/copy-plugin-confs
file=encrypt-bug.jpg
rm -rf ${cwd}/tmp/*
echo "${cwd}/build/src" >${cwd}/tmp/file-list

# Build and install the test plugin
cd ${cwd}/build/src/plugins/fd
make
if [ $? -ne 0 ]; then
   print_debug "Failed to build test plugin!"
   exit 1
fi

make install-test-plugin
if [ $? -ne 0 ]; then
   print_debug "Failed to install test plugin!"
   exit 1
fi

cd ${cwd}

start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@output /dev/null
messages
@$out $tmp/log1.out
label storage=File1 volume=TestVolume001
run job=$JobName storage=File1 yes
wait
messages
@$out $tmp/log2.out
.jlist jobs
sql
SELECT EmailSubject, EmailFrom, EmailTo, JobId, FileIndex FROM MetaEmail;


@$out $tmp/log3.out
sql
SELECT AttachmentName, JobId, FileIndex FROM MetaAttachment;

quit
END_OF_DATA

run_bacula
stop_bacula

# Temporary check, to replace with list command
nb=`grep eric@bacula $tmp/log2.out | wc -l`
if [ $nb != 2 ]; then
    print_debug "ERROR: Should find two emails in the catalog"
    estat=1
fi


end_test
