#!/bin/sh
#
# Copyright (C) 2000-2022 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
. scripts/functions

if [ $# -ne 0 ]; then
   echo "$@" >> $tmp/dummy_bsmtp.out
fi

if [ "$1" != /dev/null ]; then
	while read line ; do
	   echo "${line}" >> $tmp/dummy_bsmtp.out
	done
fi

exit 0
