.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BDIRJSON 8 "12 September 2023" "Eric Bollengier" "Network backup, utilities"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
 bdirjson \- Bacula's JSON configuration export tool
.SH SYNOPSIS
.B bdirjson
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B bdirjson
command.
.br
This is a simple program that will allow you to dump the Bacula Director configuration in JSON format.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics,
.\" respectively.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-?
Show version and usage of program.
.TP
.BI \-d\  nn
Set debug level to \fInn\fP.
.TP
.BI \-dt
Print timestamp in debug output
.TP
.BI \-r\ <res>
Get resource type
.TP
.BI \-n\ <name>
Get resource name
.TP
.BI \-l\ <dirs>
Get only directives matching dirs (use with \-r)
.TP
.BI \-D
Get only data
.TP
.BI \-R
Do not apply JobDefs to Job
.TP
.BI \-c\ <file>
Set configuration file to file
.TP
.BI \-d\ <nn>
Set debug level to <nn>
.TP
.BI \-dt
Print timestamp in debug output
.TP
.BI \-t
Read configuration and exit
.TP
.BI \-s
Output in show text format
.TP
.BI \-v
Verbose user messages
.br
.SH AUTHOR
This manual page was written by Eric Bollengier
.nh
<eric@baculasystems.com>.
This man page document is released under the BSD 2-Clause license.
